/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.frontend;

/**
 *
 * @author rafael-cayax
 */
public class LatinusIDE extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(LatinusIDE.class.getName());

    /**
     * Creates new form LatinusIDE
     */
    public LatinusIDE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        linea = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        columna = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        editor = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Codex latinus");
        setMinimumSize(new java.awt.Dimension(1000, 1000));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("Linea:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        linea.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        linea.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel1.add(linea, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("Columna:");
        jPanel1.add(jLabel3, new java.awt.GridBagConstraints());

        columna.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        columna.setText("1");
        jPanel1.add(columna, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        editor.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        editor.addCaretListener(this::editorCaretUpdate);
        jScrollPane1.setViewportView(editor);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Archivos");
        jMenu1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jMenuItem1.setText("Abrir archivo");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jMenuItem2.setText("Guardar archivo");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jMenuItem3.setText("Descargar archivo (.pig)");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Graficas");
        jMenu2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jMenuItem4.setText("Grafica AST");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jMenuItem5.setText("Grafica tabla de simbolos");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jMenuItem6.setText("Grafica pila de procesos");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editorCaretUpdate(javax.swing.event.CaretEvent evt) {// GEN-FIRST:event_editorCaretUpdate
        try {
            int pos = editor.getCaretPosition();
            var inter = editor.getDocument().getDefaultRootElement();
            int lineaV = inter.getElementIndex(pos) + 1;
            int columnaV = pos - inter.getElement(lineaV - 1).getStartOffset() + 1;
            linea.setText(lineaV + "");
            columna.setText(columnaV + "");
        } catch (Exception e) {
            linea.setText("--");
            columna.setText("--");
        }
    }// GEN-LAST:event_editorCaretUpdate

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel columna;
    private javax.swing.JTextPane editor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel linea;
    // End of variables declaration//GEN-END:variables
}
