/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.frontend;

import com.mycompany.pila.AccionPila;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayDeque;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author rafael-cayax
 */
public class PilaFrontend extends javax.swing.JDialog {
    private final ArrayDeque<AccionPila> siguientes;
    private final ArrayDeque<AccionPila> pila;
    private int estadoActual = 1;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PilaFrontend.class.getName());

    /**
     * Creates new form PilaFrontend
     */
    public PilaFrontend(java.awt.Frame parent, boolean modal, ArrayDeque<AccionPila> siguientes) {
        super(parent, modal);
        this.pila = new ArrayDeque<>();
        initComponents();
        this.siguientes = siguientes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        btnSigui = new javax.swing.JButton();
        estado = new javax.swing.JLabel();
        btnAtras20 = new javax.swing.JButton();
        btnSigui20 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pilaVisual = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        pilaVacia = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pila");
        setMinimumSize(new java.awt.Dimension(600, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnAtras.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.setEnabled(false);
        btnAtras.addActionListener(this::btnAtrasActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 40);
        jPanel1.add(btnAtras, gridBagConstraints);

        btnSigui.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnSigui.setText("Siguiente");
        btnSigui.addActionListener(this::btnSiguiActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 40);
        jPanel1.add(btnSigui, gridBagConstraints);

        estado.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        estado.setText("Estado 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        jPanel1.add(estado, gridBagConstraints);

        btnAtras20.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnAtras20.setText("-20");
        btnAtras20.setEnabled(false);
        btnAtras20.addActionListener(this::btnAtras20ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 40);
        jPanel1.add(btnAtras20, gridBagConstraints);

        btnSigui20.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btnSigui20.setText("+20");
        btnSigui20.addActionListener(this::btnSigui20ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 40);
        jPanel1.add(btnSigui20, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jSplitPane1.setDividerLocation(350);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(22, 100));

        log.setEditable(false);
        log.setBackground(java.awt.Color.black);
        log.setColumns(20);
        log.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        log.setForeground(java.awt.Color.white);
        log.setRows(5);
        log.setText("Log:");
        jScrollPane1.setViewportView(log);

        jSplitPane1.setRightComponent(jScrollPane1);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 200, 40, 100));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setMinimumSize(new java.awt.Dimension(700, 10));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(150, 500));
        jScrollPane2.setViewportView(pilaVisual);

        pilaVisual.setBackground(new java.awt.Color(255, 242, 204));
        pilaVisual.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pilaVisual.setLayout(new javax.swing.BoxLayout(pilaVisual, javax.swing.BoxLayout.Y_AXIS));
        pilaVisual.add(filler1);

        pilaVacia.setOpaque(false);
        pilaVacia.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>Pila<br>Vacia</html>");
        pilaVacia.add(jLabel1, java.awt.BorderLayout.CENTER);

        pilaVisual.add(pilaVacia);

        jScrollPane2.setViewportView(pilaVisual);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.LINE_END);

        jSplitPane1.setLeftComponent(jPanel4);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        estado.setText("Estado " + --estadoActual);
        AccionPila viejo = pila.getLast();
        viejo.desapilar(this);
        siguientes.addFirst(viejo);
        if(pila.isEmpty()) {
            btnAtras.setEnabled(false);
            btnAtras20.setEnabled(false);
        }
        if(!btnSigui.isEnabled()) {
            btnSigui.setEnabled(true);
            btnSigui20.setEnabled(true);
        }
        if(pilaVisual.getComponentCount() == 1) pilaVisual.add(pilaVacia);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnSiguiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguiActionPerformed
        estado.setText("Estado " + ++estadoActual);
        if(pilaVisual.getComponentCount() == 2) pilaVisual.remove(1);
        AccionPila actual = siguientes.removeFirst();
        if(!btnAtras.isEnabled()) {
            btnAtras.setEnabled(true);
            btnAtras20.setEnabled(true);
        }
        if(siguientes.isEmpty()) {
            btnSigui20.setEnabled(false);
            btnSigui.setEnabled(false);
        }
        actual.apilar(this);
    }//GEN-LAST:event_btnSiguiActionPerformed

    private void btnAtras20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras20ActionPerformed
        for (int i = 0; i < 20 && !pila.isEmpty(); i++) {
            btnAtrasActionPerformed(evt);
        }
    }//GEN-LAST:event_btnAtras20ActionPerformed

    private void btnSigui20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigui20ActionPerformed
        for (int i = 0; i < 20 && !siguientes.isEmpty(); i++) {
            btnSiguiActionPerformed(evt);
        }
    }//GEN-LAST:event_btnSigui20ActionPerformed

    public void agregarPila(AccionPila a){
        agregarPila(a, true);
    }
    
    public void agregarPila(AccionPila a, boolean visual){
        pila.add(a);
        if(!visual) return;
        var nuevo = new JLabel();
        var elemento = a.getEleApilar();
        nuevo.setFont(new Font("Liberation Sans", 0, 15));
        nuevo.setForeground(new Color(0, 0, 0));
        nuevo.setHorizontalAlignment(SwingConstants.CENTER);
        nuevo.setOpaque(true);
        nuevo.setMaximumSize(new Dimension(Integer.MAX_VALUE, 30));
        nuevo.setPreferredSize(new Dimension(80, 30));
        nuevo.setText(elemento.getSimbolo());
        if(elemento.isTerminal()){
            nuevo.setBackground(new Color(248, 206, 204));
        } else {
            nuevo.setBackground(new Color(218, 232, 252));
        }
        pilaVisual.add(nuevo, 1);
        pilaVisual.add(Box.createVerticalStrut(5), 2);
        pilaVisual.revalidate();
        pilaVisual.repaint();
    }
    
    public void desApilarAccept(){
        pila.removeLast();
    }
    
    public AccionPila desApilar(){
        pilaVisual.remove(2);
        pilaVisual.remove(1);
        pilaVisual.revalidate();
        pilaVisual.repaint();
        return pila.removeLast();
    }
    
    public void eliminarDelLog(int longitud) {
        int longitudLog = log.getText().length();
        log.replaceRange("", longitudLog - longitud, longitudLog);
    }
    
    public void agregarAlLog(String texto){
        log.append("\n   "+texto);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnAtras20;
    private javax.swing.JButton btnSigui;
    private javax.swing.JButton btnSigui20;
    private javax.swing.JLabel estado;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea log;
    private javax.swing.JPanel pilaVacia;
    private javax.swing.JPanel pilaVisual;
    // End of variables declaration//GEN-END:variables
}
